# Generated by Django 4.1.3 on 2023-11-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LlmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='模型名称')),
                ('tags', models.CharField(max_length=50, verbose_name='模型标签')),
                ('path', models.CharField(max_length=100, verbose_name='模型地址')),
                ('publisher', models.CharField(max_length=50, verbose_name='模型发布者')),
                ('introduce', models.TextField(verbose_name='模型介绍')),
            ],
        ),
    ]
